import { FlowDefinition } from "./types";

export const TEMPLATES: Record<string, FlowDefinition> = {
  "Basic: Google Search (GoTo → Type → Click)": {
    meta: { name: "Basic: Google Search", version: "1.0" },
    nodes: [
      {
        id: "goto1",
        type: "GoTo",
        position: { x: 80, y: 80 },
        data: { label: "Go To URL", kind: "GoTo", config: { url: "https://www.google.com" } },
      },
      {
        id: "type1",
        type: "Type",
        position: { x: 360, y: 80 },
        data: { label: "Type", kind: "Type", config: { xpath: "//input[@name='q']", text: "hello world" } },
      },
      {
        id: "click1",
        type: "Click",
        position: { x: 640, y: 80 },
        data: { label: "Click", kind: "Click", config: { xpath: "//input[@name='btnK']", index: 0 } },
      },
    ],
    edges: [
      { id: "e1", source: "goto1", target: "type1", label: "then" },
      { id: "e2", source: "type1", target: "click1", label: "then" },
    ],
  },
  "Form Fill with Select & Scroll": {
    meta: { name: "Form Fill with Select & Scroll", version: "1.0" },
    nodes: [
      {
        id: "goto1",
        type: "GoTo",
        position: { x: 80, y: 80 },
        data: { label: "Go To Form", kind: "GoTo", config: { url: "https://example.com/form" } },
      },
      {
        id: "type1",
        type: "Type",
        position: { x: 280, y: 80 },
        data: { label: "Enter Name", kind: "Type", config: { xpath: "//input[@name='fullname']", text: "John Doe" } },
      },
      {
        id: "select1",
        type: "Select",
        position: { x: 480, y: 80 },
        data: { label: "Select Country", kind: "Select", config: { xpath: "//select[@name='country']", selectBy: "text", selectValue: "United States" } },
      },
      {
        id: "scroll1",
        type: "ScrollTo",
        position: { x: 680, y: 80 },
        data: { label: "Scroll to Submit", kind: "ScrollTo", config: { scrollType: "element", xpath: "//button[@type='submit']" } },
      },
      {
        id: "click1",
        type: "Click",
        position: { x: 880, y: 80 },
        data: { label: "Submit Form", kind: "Click", config: { xpath: "//button[@type='submit']" } },
      },
    ],
    edges: [
      { id: "e1", source: "goto1", target: "type1" },
      { id: "e2", source: "type1", target: "select1" },
      { id: "e3", source: "select1", target: "scroll1" },
      { id: "e4", source: "scroll1", target: "click1" },
    ],
  },
  "Data Extraction with Loop": {
    meta: { name: "Data Extraction with Loop", version: "1.0" },
    nodes: [
      {
        id: "goto1",
        type: "GoTo",
        position: { x: 80, y: 80 },
        data: { label: "Go To Page", kind: "GoTo", config: { url: "https://example.com/products" } },
      },
      {
        id: "wait1",
        type: "Wait",
        position: { x: 280, y: 80 },
        data: { label: "Wait for Products", kind: "Wait", config: { waitType: "element", xpath: "//div[@class='product']", timeout: 5000 } },
      },
      {
        id: "loop1",
        type: "Loop",
        position: { x: 480, y: 80 },
        data: { label: "Loop Products", kind: "Loop", config: { items: ["product1", "product2", "product3"], iteratorName: "product" } },
      },
      {
        id: "extract1",
        type: "Extract",
        position: { x: 680, y: 80 },
        data: { label: "Extract Title", kind: "Extract", config: { xpath: "//h2[@class='title']", extractType: "text" } },
      },
      {
        id: "log1",
        type: "Log",
        position: { x: 880, y: 80 },
        data: { label: "Log Product", kind: "Log", config: { logLevel: "info", message: "Product extracted successfully" } },
      },
    ],
    edges: [
      { id: "e1", source: "goto1", target: "wait1" },
      { id: "e2", source: "wait1", target: "loop1" },
      { id: "e3", source: "loop1", target: "extract1" },
      { id: "e4", source: "extract1", target: "log1" },
    ],
  },
  "Multi-Tab Navigation": {
    meta: { name: "Multi-Tab Navigation", version: "1.0" },
    nodes: [
      {
        id: "goto1",
        type: "GoTo",
        position: { x: 80, y: 80 },
        data: { label: "Open First Site", kind: "GoTo", config: { url: "https://example.com" } },
      },
      {
        id: "nav1",
        type: "Navigation",
        position: { x: 280, y: 80 },
        data: { label: "Open New Tab", kind: "Navigation", config: { action: "newTab" } },
      },
      {
        id: "goto2",
        type: "GoTo",
        position: { x: 480, y: 80 },
        data: { label: "Open Second Site", kind: "GoTo", config: { url: "https://another-site.com" } },
      },
      {
        id: "switch1",
        type: "SwitchTab",
        position: { x: 680, y: 80 },
        data: { label: "Switch to First Tab", kind: "SwitchTab", config: { tabIndex: 0 } },
      },
      {
        id: "extract1",
        type: "Extract",
        position: { x: 880, y: 80 },
        data: { label: "Extract from First", kind: "Extract", config: { xpath: "//title", extractType: "text" } },
      },
    ],
    edges: [
      { id: "e1", source: "goto1", target: "nav1" },
      { id: "e2", source: "nav1", target: "goto2" },
      { id: "e3", source: "goto2", target: "switch1" },
      { id: "e4", source: "switch1", target: "extract1" },
    ],
  },
  "Conditional Flow with If/Else": {
    meta: { name: "Conditional Flow with If/Else", version: "1.0" },
    nodes: [
      {
        id: "goto1",
        type: "GoTo",
        position: { x: 80, y: 80 },
        data: { label: "Go To Page", kind: "GoTo", config: { url: "https://example.com" } },
      },
      {
        id: "if1",
        type: "If",
        position: { x: 280, y: 80 },
        data: { label: "Check Login Button", kind: "If", config: { condition: "element_exists", xpath: "//button[@id='login']" } },
      },
      {
        id: "click1",
        type: "Click",
        position: { x: 480, y: 40 },
        data: { label: "Click Login", kind: "Click", config: { xpath: "//button[@id='login']" } },
      },
      {
        id: "else1",
        type: "Else",
        position: { x: 480, y: 120 },
        data: { label: "Else", kind: "Else" },
      },
      {
        id: "log1",
        type: "Log",
        position: { x: 680, y: 120 },
        data: { label: "Log No Login", kind: "Log", config: { logLevel: "warn", message: "Login button not found" } },
      },
    ],
    edges: [
      { id: "e1", source: "goto1", target: "if1" },
      { id: "e2", source: "if1", target: "click1", label: "true" },
      { id: "e3", source: "if1", target: "else1", label: "false" },
      { id: "e4", source: "else1", target: "log1" },
    ],
  },
  "Frame Handling": {
    meta: { name: "Frame Handling", version: "1.0" },
    nodes: [
      {
        id: "goto1",
        type: "GoTo",
        position: { x: 80, y: 80 },
        data: { label: "Go To Page", kind: "GoTo", config: { url: "https://example.com/iframe-page" } },
      },
      {
        id: "switch1",
        type: "SwitchFrame",
        position: { x: 280, y: 80 },
        data: { label: "Enter iFrame", kind: "SwitchFrame", config: { frameType: "enter", frameSelector: "iframe#content" } },
      },
      {
        id: "type1",
        type: "Type",
        position: { x: 480, y: 80 },
        data: { label: "Type in Frame", kind: "Type", config: { xpath: "//input[@name='search']", text: "test" } },
      },
      {
        id: "switch2",
        type: "SwitchFrame",
        position: { x: 680, y: 80 },
        data: { label: "Exit to Main", kind: "SwitchFrame", config: { frameType: "exit" } },
      },
      {
        id: "click1",
        type: "Click",
        position: { x: 880, y: 80 },
        data: { label: "Click Outside", kind: "Click", config: { xpath: "//button[@id='submit']" } },
      },
    ],
    edges: [
      { id: "e1", source: "goto1", target: "switch1" },
      { id: "e2", source: "switch1", target: "type1" },
      { id: "e3", source: "type1", target: "switch2" },
      { id: "e4", source: "switch2", target: "click1" },
    ],
  },
  "X (Twitter) Login": {
    meta: { name: "X (Twitter) Login", version: "1.0" },
    nodes: [
      {
        id: "goto1",
        type: "GoTo",
        position: { x: 80, y: 80 },
        data: { label: "Go to X.com", kind: "GoTo", config: { url: "https://x.com/login" } },
      },
      {
        id: "wait1",
        type: "Wait",
        position: { x: 280, y: 80 },
        data: { label: "Wait for Login Form", kind: "Wait", config: { waitType: "element", xpath: "//input[@autocomplete='username']", timeout: 5000 } },
      },
      {
        id: "type1",
        type: "Type",
        position: { x: 480, y: 80 },
        data: { label: "Enter Username/Email", kind: "Type", config: { xpath: "//input[@autocomplete='username']", text: "your_username" } },
      },
      {
        id: "click1",
        type: "Click",
        position: { x: 680, y: 80 },
        data: { label: "Click Next", kind: "Click", config: { xpath: "//span[text()='Next']//ancestor::div[@role='button']" } },
      },
      {
        id: "wait2",
        type: "Wait",
        position: { x: 880, y: 80 },
        data: { label: "Wait for Password", kind: "Wait", config: { waitType: "element", xpath: "//input[@type='password']", timeout: 5000 } },
      },
      {
        id: "type2",
        type: "Type",
        position: { x: 1080, y: 80 },
        data: { label: "Enter Password", kind: "Type", config: { xpath: "//input[@type='password']", text: "your_password" } },
      },
      {
        id: "click2",
        type: "Click",
        position: { x: 1280, y: 80 },
        data: { label: "Click Log in", kind: "Click", config: { xpath: "//span[text()='Log in']//ancestor::div[@role='button']" } },
      },
      {
        id: "wait3",
        type: "Wait",
        position: { x: 1480, y: 80 },
        data: { label: "Wait for Home", kind: "Wait", config: { waitType: "element", xpath: "//a[@aria-label='X']", timeout: 10000 } },
      },
      {
        id: "log1",
        type: "Log",
        position: { x: 1680, y: 80 },
        data: { label: "Login Success", kind: "Log", config: { logLevel: "info", message: "Successfully logged in to X (Twitter)" } },
      },
    ],
    edges: [
      { id: "e1", source: "goto1", target: "wait1" },
      { id: "e2", source: "wait1", target: "type1" },
      { id: "e3", source: "type1", target: "click1" },
      { id: "e4", source: "click1", target: "wait2" },
      { id: "e5", source: "wait2", target: "type2" },
      { id: "e6", source: "type2", target: "click2" },
      { id: "e7", source: "click2", target: "wait3" },
      { id: "e8", source: "wait3", target: "log1" },
    ],
  },
  "X (Twitter) Seeding - Like & Retweet": {
    meta: { name: "X (Twitter) Seeding - Like & Retweet", version: "1.0" },
    nodes: [
      {
        id: "goto1",
        type: "GoTo",
        position: { x: 80, y: 80 },
        data: { label: "Go to X Home", kind: "GoTo", config: { url: "https://x.com/home" } },
      },
      {
        id: "wait1",
        type: "Wait",
        position: { x: 280, y: 80 },
        data: { label: "Wait for Feed", kind: "Wait", config: { waitType: "element", xpath: "//article[@data-testid='tweet']", timeout: 5000 } },
      },
      {
        id: "scroll1",
        type: "ScrollTo",
        position: { x: 480, y: 80 },
        data: { label: "Scroll Down", kind: "ScrollTo", config: { scrollType: "position", scrollX: 0, scrollY: 500 } },
      },
      {
        id: "wait2",
        type: "Wait",
        position: { x: 680, y: 80 },
        data: { label: "Wait 2 seconds", kind: "Wait", config: { waitType: "time", timeout: 2000 } },
      },
      {
        id: "click1",
        type: "Click",
        position: { x: 880, y: 80 },
        data: { label: "Like Tweet", kind: "Click", config: { xpath: "(//div[@data-testid='like'])[1]" } },
      },
      {
        id: "wait3",
        type: "Wait",
        position: { x: 1080, y: 80 },
        data: { label: "Wait 1 second", kind: "Wait", config: { waitType: "time", timeout: 1000 } },
      },
      {
        id: "click2",
        type: "Click",
        position: { x: 1280, y: 80 },
        data: { label: "Retweet", kind: "Click", config: { xpath: "(//div[@data-testid='retweet'])[1]" } },
      },
      {
        id: "wait4",
        type: "Wait",
        position: { x: 1480, y: 80 },
        data: { label: "Wait for Menu", kind: "Wait", config: { waitType: "element", xpath: "//span[text()='Repost']", timeout: 2000 } },
      },
      {
        id: "click3",
        type: "Click",
        position: { x: 1680, y: 80 },
        data: { label: "Confirm Retweet", kind: "Click", config: { xpath: "//span[text()='Repost']" } },
      },
      {
        id: "log1",
        type: "Log",
        position: { x: 1880, y: 80 },
        data: { label: "Action Complete", kind: "Log", config: { logLevel: "info", message: "Tweet liked and retweeted successfully" } },
      },
    ],
    edges: [
      { id: "e1", source: "goto1", target: "wait1" },
      { id: "e2", source: "wait1", target: "scroll1" },
      { id: "e3", source: "scroll1", target: "wait2" },
      { id: "e4", source: "wait2", target: "click1" },
      { id: "e5", source: "click1", target: "wait3" },
      { id: "e6", source: "wait3", target: "click2" },
      { id: "e7", source: "click2", target: "wait4" },
      { id: "e8", source: "wait4", target: "click3" },
      { id: "e9", source: "click3", target: "log1" },
    ],
  },
  "X (Twitter) Follow Users": {
    meta: { name: "X (Twitter) Follow Users", version: "1.0" },
    nodes: [
      {
        id: "goto1",
        type: "GoTo",
        position: { x: 80, y: 80 },
        data: { label: "Go to Profile", kind: "GoTo", config: { url: "https://x.com/elonmusk" } },
      },
      {
        id: "wait1",
        type: "Wait",
        position: { x: 280, y: 80 },
        data: { label: "Wait for Profile", kind: "Wait", config: { waitType: "element", xpath: "//div[@data-testid='placementTracking']", timeout: 5000 } },
      },
      {
        id: "if1",
        type: "If",
        position: { x: 480, y: 80 },
        data: { label: "Check Follow Button", kind: "If", config: { condition: "element_exists", xpath: "//span[text()='Follow']" } },
      },
      {
        id: "click1",
        type: "Click",
        position: { x: 680, y: 40 },
        data: { label: "Click Follow", kind: "Click", config: { xpath: "//span[text()='Follow']//ancestor::div[@role='button']" } },
      },
      {
        id: "wait2",
        type: "Wait",
        position: { x: 880, y: 40 },
        data: { label: "Wait 2 seconds", kind: "Wait", config: { waitType: "time", timeout: 2000 } },
      },
      {
        id: "log1",
        type: "Log",
        position: { x: 1080, y: 40 },
        data: { label: "Followed", kind: "Log", config: { logLevel: "info", message: "Successfully followed user" } },
      },
      {
        id: "else1",
        type: "Else",
        position: { x: 680, y: 120 },
        data: { label: "Else", kind: "Else" },
      },
      {
        id: "log2",
        type: "Log",
        position: { x: 880, y: 120 },
        data: { label: "Already Following", kind: "Log", config: { logLevel: "info", message: "Already following this user" } },
      },
    ],
    edges: [
      { id: "e1", source: "goto1", target: "wait1" },
      { id: "e2", source: "wait1", target: "if1" },
      { id: "e3", source: "if1", target: "click1", label: "true" },
      { id: "e4", source: "click1", target: "wait2" },
      { id: "e5", source: "wait2", target: "log1" },
      { id: "e6", source: "if1", target: "else1", label: "false" },
      { id: "e7", source: "else1", target: "log2" },
    ],
  },
  "X (Twitter) Post Tweet": {
    meta: { name: "X (Twitter) Post Tweet", version: "1.0" },
    nodes: [
      {
        id: "goto1",
        type: "GoTo",
        position: { x: 80, y: 80 },
        data: { label: "Go to X Home", kind: "GoTo", config: { url: "https://x.com/home" } },
      },
      {
        id: "wait1",
        type: "Wait",
        position: { x: 280, y: 80 },
        data: { label: "Wait for Compose", kind: "Wait", config: { waitType: "element", xpath: "//a[@aria-label='Post']", timeout: 5000 } },
      },
      {
        id: "click1",
        type: "Click",
        position: { x: 480, y: 80 },
        data: { label: "Click Post Button", kind: "Click", config: { xpath: "//a[@aria-label='Post']" } },
      },
      {
        id: "wait2",
        type: "Wait",
        position: { x: 680, y: 80 },
        data: { label: "Wait for Editor", kind: "Wait", config: { waitType: "element", xpath: "//div[@data-testid='tweetTextarea_0']", timeout: 3000 } },
      },
      {
        id: "type1",
        type: "Type",
        position: { x: 880, y: 80 },
        data: { label: "Type Tweet", kind: "Type", config: { xpath: "//div[@data-testid='tweetTextarea_0']//div[@contenteditable='true']", text: "Hello X! This is my automated tweet." } },
      },
      {
        id: "wait3",
        type: "Wait",
        position: { x: 1080, y: 80 },
        data: { label: "Wait 1 second", kind: "Wait", config: { waitType: "time", timeout: 1000 } },
      },
      {
        id: "click2",
        type: "Click",
        position: { x: 1280, y: 80 },
        data: { label: "Send Tweet", kind: "Click", config: { xpath: "//span[text()='Post']//ancestor::div[@role='button'][@data-testid='tweetButtonInline']" } },
      },
      {
        id: "wait4",
        type: "Wait",
        position: { x: 1480, y: 80 },
        data: { label: "Wait for Success", kind: "Wait", config: { waitType: "time", timeout: 3000 } },
      },
      {
        id: "log1",
        type: "Log",
        position: { x: 1680, y: 80 },
        data: { label: "Tweet Posted", kind: "Log", config: { logLevel: "info", message: "Tweet posted successfully" } },
      },
    ],
    edges: [
      { id: "e1", source: "goto1", target: "wait1" },
      { id: "e2", source: "wait1", target: "click1" },
      { id: "e3", source: "click1", target: "wait2" },
      { id: "e4", source: "wait2", target: "type1" },
      { id: "e5", source: "type1", target: "wait3" },
      { id: "e6", source: "wait3", target: "click2" },
      { id: "e7", source: "click2", target: "wait4" },
      { id: "e8", source: "wait4", target: "log1" },
    ],
  },
  "X (Twitter) Search & Interact": {
    meta: { name: "X (Twitter) Search & Interact", version: "1.0" },
    nodes: [
      {
        id: "goto1",
        type: "GoTo",
        position: { x: 80, y: 80 },
        data: { label: "Go to X", kind: "GoTo", config: { url: "https://x.com/explore" } },
      },
      {
        id: "wait1",
        type: "Wait",
        position: { x: 280, y: 80 },
        data: { label: "Wait for Search", kind: "Wait", config: { waitType: "element", xpath: "//input[@placeholder='Search']", timeout: 5000 } },
      },
      {
        id: "type1",
        type: "Type",
        position: { x: 480, y: 80 },
        data: { label: "Enter Search Term", kind: "Type", config: { xpath: "//input[@placeholder='Search']", text: "#AI #Technology" } },
      },
      {
        id: "click1",
        type: "Click",
        position: { x: 680, y: 80 },
        data: { label: "Press Enter", kind: "Click", config: { xpath: "//input[@placeholder='Search']" } },
      },
      {
        id: "wait2",
        type: "Wait",
        position: { x: 880, y: 80 },
        data: { label: "Wait for Results", kind: "Wait", config: { waitType: "element", xpath: "//article[@data-testid='tweet']", timeout: 5000 } },
      },
      {
        id: "loop1",
        type: "Loop",
        position: { x: 1080, y: 80 },
        data: { label: "Loop 5 Tweets", kind: "Loop", config: { items: ["1", "2", "3", "4", "5"], iteratorName: "index" } },
      },
      {
        id: "scroll1",
        type: "ScrollTo",
        position: { x: 1280, y: 80 },
        data: { label: "Scroll to Tweet", kind: "ScrollTo", config: { scrollType: "element", xpath: "(//article[@data-testid='tweet'])[${index}]" } },
      },
      {
        id: "click2",
        type: "Click",
        position: { x: 1480, y: 80 },
        data: { label: "Like Tweet", kind: "Click", config: { xpath: "(//div[@data-testid='like'])[${index}]" } },
      },
      {
        id: "wait3",
        type: "Wait",
        position: { x: 1680, y: 80 },
        data: { label: "Wait Between Likes", kind: "Wait", config: { waitType: "time", timeout: 2000 } },
      },
    ],
    edges: [
      { id: "e1", source: "goto1", target: "wait1" },
      { id: "e2", source: "wait1", target: "type1" },
      { id: "e3", source: "type1", target: "click1" },
      { id: "e4", source: "click1", target: "wait2" },
      { id: "e5", source: "wait2", target: "loop1" },
      { id: "e6", source: "loop1", target: "scroll1" },
      { id: "e7", source: "scroll1", target: "click2" },
      { id: "e8", source: "click2", target: "wait3" },
      { id: "e9", source: "wait3", target: "loop1", label: "next" },
    ],
  },
};
